# Generated by Django 4.2 on 2023-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
