# Generated by Django 4.2 on 2023-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_alter_loginrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='is_consumed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
